version: '3.3'

x-log: &logging
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "10"

services:
  viewer:
    <<: *logging
    image: ohif/viewer
    container_name: viewer
    depends_on:
      - app
    restart: always
    ports:
      - 3000:80
    volumes:
        - ./app/conf/viewer.js:/usr/share/nginx/html/app-config.js:ro
        - ./app/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
  app:
    <<: *logging
    image: osimis/orthanc
    restart: always
    depends_on: 
      - db
    volumes:
      - orthanc:/var/lib/orthanc/db
      #учесть размещение на объемном диске
      - /tmp/Orthanc:/tmp/Orthanc
      - ./app/conf/conf.json:/etc/orthanc/conf.json:ro
    ports:
      - "4242:4242"
      # - "8042:8042"
  db:
    <<: *logging
    image: postgres:13
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=groot
      - POSTGRES_PASSWORD=c5xO^44bTI
      - POSTGRES_DB=orthanc
volumes:
  postgres:
  orthanc:
    # driver: local
    # driver_opts:
    #     o: bind
    #     type: none
    #     device: /opt/data01/otrhanc_data/
