version: '3.1'
services:
    orthanc:
        volumes: 
#            - ./app/backup:/backup 
#            - ./app/plugins:/usr/share/orthanc/build-plugins
           - ./app/plugins:/usr/share/orthanc/plugins
           - ./plugins.json:/etc/orthanc/plugins.json
           - ./storage.json:/etc/orthanc/storage.json
           - ./http.json:/etc/orthanc/http.json
        container_name: covid_orthanc_prod
        build: .
        restart: always
        ports:
            - "4242:4242"
            - "8042:8042"