version: '3.8'

x-log: &logging
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "10"

x-env-orthanc: &orthanc
  ORTHANC__AET:   ${ORTHANC__AET:-orthanc_rd}
  ORTHANC__NAME:  ${ORTHANC__NAME:-orthanc}
  ORTHANC__POSTGRESQL__PASSWORD: ${POSTGRES_PASSWORD}
  ORTHANC__POSTGRESQL__ENABLE_INDEX: "true"
  ORTHANC__POSTGRESQL__ENABLE_STORAGE: "false"
  ORTHANC__POSTGRESQL__ENABLE_SSL: "false"
  ORTHANC__POSTGRESQL__HOST: "db"
  VERBOSE_ENABLED: "true"
  STONE_WEB_VIEWER_PLUGIN_ENABLED: "true"
  DICOM_WEB_PLUGIN_ENABLED: "true"
  MALLOC_ARENA_MAX: 2
  ORTHANC_NAME: "orthanc"
  DW_ENABLED: "true"

services:
  proxy:
    build:
      context: ./app
      dockerfile: Dockerfile-nginx
    image: orthanc-proxy
    restart: unless-stopped
    tmpfs:
      - /var/cache/nginx/proxy_temp:size=1G
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - front
  app:
    <<: *logging
    build: 
      context: ./app
      dockerfile: Dockerfile-orthanc
    image: orthanc
    container_name: orthanc
    restart: unless-stopped
    volumes:
      - orthanc:/var/lib/orthanc/db
    environment:
      TZ: "Europe/Moscow"
      <<: *orthanc
    tmpfs:
      - /tmp/Orthanc:size=1G
    depends_on:
      - db
    ports:
      - 4242:4242
    networks:
      - front
      - back

  db:
    <<: *logging
    image: postgres:13
    restart: unless-stopped
    container_name: orthanc-db
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      TZ: "Europe/Moscow"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: orthanc
    networks:
      - back

networks:
  front:
  back:

volumes:
  postgres:
  orthanc:
    driver_opts:
      o: bind
      type: none
      # задает место хранения данных орфанка.
      # папка должна существовать
      device: ${ORTHANC_VOLUMES_DATA:-/mnt/datasets}
