version: '3.3'

x-log: &logging
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "10"

services:
  orthanc:
      <<: *logging
      image: osimis/orthanc
      depends_on:
        - s3
      restart: always
      volumes:
        - /mnt/tmp:/var/lib/orthanc/db:rshared
        #учесть размещение на объемном диске
        - /tmp/Orthanc:/tmp/Orthanc
        - ./app/conf/conf.json:/etc/orthanc/conf.json
      ports:
        - "4242:4242"
        - "8042:8042"
  # db:
